name: Build and Push to DockerHub

on:
  push:
    branches:
      - chains/coreum

env:
  BDJUNO_IMAGE_NAME: bdjuno
  HASURA_IMAGE_NAME: hasura
  ORG: coreumfoundation

jobs:
  setup-build-publish-webhook:
    name: Setup, Build, Publish, Webhook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set variables
        # if git tag is present, set it to BDJUNO_FULL_TAG_NAME and HASURA_FULL_TAG_NAME, else put empty string
        run: |
          echo "SHA8=${GITHUB_SHA::8}" >> $GITHUB_ENV
          export BDJUNO_FULL_TAG_NAME=${{ (startsWith(github.ref, 'refs/tags/') && format('{0}/{1}:{2}', env.ORG, env.BDJUNO_IMAGE_NAME, github.ref_name)) || '' }}
          echo "BDJUNO_FULL_TAG_NAME=$BDJUNO_FULL_TAG_NAME" >> $GITHUB_ENV
          export HASURA_FULL_TAG_NAME=${{ (startsWith(github.ref, 'refs/tags/') && format('{0}/{1}:{2}', env.ORG, env.HASURA_IMAGE_NAME, github.ref_name)) || '' }}
          echo "HASURA_FULL_TAG_NAME=$HASURA_FULL_TAG_NAME" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bdjuno
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          # if tag is an empty string, plugin will skip that tag.
          tags: |
            ${{ env.ORG }}/${{ env.BDJUNO_IMAGE_NAME }}:latest
            ${{ env.ORG }}/${{ env.BDJUNO_IMAGE_NAME }}:${{ env.SHA8 }}
            ${{ env.BDJUNO_FULL_TAG_NAME }}

      - name: Build and push hasura
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.hasura
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:latest
            ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:${{ env.SHA8 }}
            ${{ env.HASURA_FULL_TAG_NAME }}

